// src/types/payment.ts

export interface CartItem {
  productId: string | number;
  name: string;
  price: number; // Price per unit at the time of adding to cart
  quantity: number;
  image?: string;
  // Any other relevant product details needed in cart
}

export interface Cart {
  items: CartItem[];
  totalItems: number;
  subtotal: number; // Sum of (item.price * item.quantity)
  discount?: number;
  shippingCost?: number;
  totalAmount: number; // Final amount to be paid
  // currency: 'KWD'; // Could be fixed or dynamic
}

export interface KuwaitAddress {
  governorate: string; // Could be an enum or specific type
  area: string;
  block: string;
  street: string;
  building: string;
  apartment?: string;
  notes?: string;
  // deliveryFee?: number; // This might be calculated dynamically
}

export interface OrderDetails {
  orderId?: string; // Generated by backend or payment gateway
  items: CartItem[];
  shippingAddress: KuwaitAddress; // Or a more generic Address type if needed
  billingAddress?: KuwaitAddress; // Or a more generic Address type
  customerDetails: {
    name: string;
    email: string;
    phone: string;
    civilId?: string; // For Kuwait
  };
  paymentMethod: 'KNET' | 'CreditCard' | 'CashOnDelivery'; // Example
  subtotal: number;
  shippingCost: number;
  discount?: number;
  totalAmount: number;
  currency: string; // e.g., 'KWD'
  // KNET specific details if needed after payment attempt
  knetTransactionId?: string;
  knetPaymentStatus?: 'Pending' | 'Success' | 'Failed' | 'Cancelled';
  createdAt?: string | Date;
  updatedAt?: string | Date;
}

// For KNET utility function parameters/responses
export interface KnetPaymentRequest {
  amount: number; // in KWD, smallest unit (e.g., fils)
  orderId: string; // Your internal order ID
  customerEmail?: string;
  // Other necessary KNET parameters
  redirectUrl: string; // URL to redirect after KNET payment
  errorUrl: string; // URL to redirect if KNET process errors out before payment
}

export interface KnetPaymentResponse {
  transactionId: string;
  paymentId: string; // KNET's payment ID
  result: 'SUCCESS' | 'FAILURE' | 'PENDING' | 'CANCELLED' | 'ERROR'; // KNET result codes
  authCode?: string; // Authorization code if successful
  referenceId?: string; // Your orderId
  postDate?: string; // Date of transaction
  errorCode?: string;
  errorMessage?: string;
  // rawResponse?: any; // To store the full gateway response
}

export interface KnetRefundRequest {
  transactionId: string; // Original KNET transaction ID
  amount: number; // Amount to refund, in KWD (smallest unit)
  reason?: string;
}

export interface KnetRefundResponse {
  refundId: string;
  status: 'Success' | 'Failed' | 'Pending';
  message?: string;
  // rawResponse?: any;
}
